hide_agent_reasoning = true
model = "gpt-5-codex"
network_access = true
ask_for_approval = "never"
model_responding_effort = "medium"
web_search_request = true

[mcp_servers.serena]
args = [
    "--from",
    "git+https://github.com/oraios/serena",
    "serena",
    "start-mcp-server",
    "--context",
    "codex",
]
command = "uvx"

[projects."/Users/nohira/ghq/github.com/maro114510/moto-weather-index"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/moto-weather-index-front"]
trust_level = "trusted"

[projects."/Users/nohira/.local/share/chezmoi"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/golang_notion_api"]
trust_level = "trusted"

[projects."/Users/nohira"]
trust_level = "trusted"

[projects."/Users/nohira/sample"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/youtube_check"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/Obsidian"]
trust_level = "trusted"

[projects."/Users/nohira/.codex"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/dotfiles"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/python_sandbox"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/golang_sandbox"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/googlecloud_project"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/stock_turnback"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/python-clean-architecture"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/peco"]
trust_level = "trusted"

[projects."/Users/nohira/ghq/github.com/maro114510/slides_memo"]
trust_level = "trusted"
