# format = """
# $directory\
# [î‚´](fg:#88C0D0 bg:#394260)\
# $git_branch\
# $git_status\
# [î‚´](fg:#394260)\
# $fill\
# [î‚¶](fg:#212736)\
# $nodejs\
# $rust\
# $golang\
# $php\
# [î‚¶](fg:#1d2230 bg:#212736)\
# $time\
# [î‚¶](fg:#88C0D0 bg:#1d2230)\
# $os\
# [î‚´](fg:#88C0D0)\
# \n$character"""
# 
# add_newline = false
# 
# [fill]
# symbol = ' '
# 
# [os]
# format = "[$symbol]($style)"
# style = "fg:#2E3440 bg:#88C0D0 bold"
# disabled = false
# 
[custom.os_version]
command = "uname"
format = ' [$symbol($output)]($style)'

[os.symbols]
Macos = " ï…¹ " # nf-fa-apple
Ubuntu = " ïŒ› " # nf-linux-ubuntu
Debian = " ïŒ† " # nf-linux-debian

# [directory]
# style = "fg:#2E3440 bg:#88C0D0 bold"
# format = "[ $path ]($style)"
# truncation_length = 10
# truncate_to_repo = false
# truncation_symbol = "â€¦/"
# 
# [directory.substitutions]
# "Documents" = "ó°ˆ™ "
# "Downloads" = "ï€™ "
# "Music" = "ï€ "
# "Pictures" = "ï€¾ "
# 
[gcloud]
disabled = true

[golang]
format = '(via [$symbol($version )]($style))'

# [golang]
# symbol = "î˜§"
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
format = '(via [$symbol($version )]($style))'

[python]
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[ruby]
format = '(via [$symbol($version )]($style))'

[rust]
format = '(via [$symbol($version )]($style))'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 10
style = 'bold red'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'
